branches:
  only:
  - "/^v0.*$/"
  - codedeploy
  - master
language: python
python:
- '3.5'
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt
addons:
  postgresql: '9.4'
before_script:
- mv configs/test_settings_local.py nmid/settings_local.py
script: python manage.py migrate
deploy:
  provider: codedeploy
  access_key_id: AKIAJNYGDLOJKHOUWCAA
  secret_access_key:
    secure: GZa66dwDh7nU5F4YSJHmu+QU8W+xX3+Zp3nI3qP/MgOQmpDmxNGBRiQA3UdUHYZsz3TRZ35BRA/IHVFa97IDAVeiRgsFHvHOYtzYzIZ5WesS1KVUZZ2bK6PIJA4adA9Smd782FyBPShD+q8GCOP5yhi1T05+iKx/jgPBkeszHUczLRCernd6FQl03CfvSaeONykeAQWON2mFbNfsJtq8otYi27R2LMqvw6IxdZUKUe/18T2qACIVWzzNJIs2DdxfrD7AqmwxzL7Cp0pqhCYeSEqV+bztphkxwevSjZu034j9Jk6cMzshBCR9FBcsyPO2ds7BxW03JBz7BxeWueqsE/39zZZz8vqVAUhmpPKORDFHuZEIO3/ajrzayqrhsB41AShKOk0076E6Ky0+W+ymG7VzwM/uiOURyQlwm6R5XvSdyFTgnZ5ucalbS4VFPw80IYCOK3zR5YbvYl8e2CqbQYWmjnUqwF32VlXU3wjy10HKLkNMZPFiv6oVGMB8wIWqLN3GPz7noaJkKOIh4A1zKL4Y5jRBpAgdobEwaytJDA5eOaCcVM+fwtE4hK1fVpqTYGCV/p8b/v7ZmeVDPkBx+W29LB6lPR5Yp4/kdtCwoYLIhZuX63njRSrWfDJ2xNGGJrS1I5BzrtjEcxmoOC4bG8fW0ecmRp5YyXapxMpKBIk=
  application: nmid
  deployment_group: staging
  on:
    branch: master
